<?php
$widgetEnable = $this->getConfigValue('lofhideprice/general/enable');
$captchaSitekey = $this->getConfigValue('lofhideprice/recaptcha/recaptcha_sitekey');
$captchaTheme = $this->getConfigValue('lofhideprice/recaptcha/recaptcha_theme');
$formActionUrl = $this->getFormActionUrl();
$helper = $this->helper('Lof\HidePrice\Helper\Data');
$currPageUrl = $helper->getCurrentUrls();
 
?>
<?php if($widgetEnable){?>
<form class="form contact" style="width:800px; height:570px; background-color:#F0FFFF;" action="<?php echo $formActionUrl;?>" id="contact-form" method="post" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <input name="hideprice_id" id="hideprice_id" title="<?php /* @escapeNotVerified */ echo __('Hide Price') ?>" class="input-text" type="hidden" />
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo $this->getData('cc_title') ?></span></legend><br />
        <div class="field note no-label"><?php /* @escapeNotVerified */ echo $this->getData('cc_content') ?></div>

        <div>
            <div class="col-sm-12">
                <label class="label" for="entity_id"><span><?php /* @escapeNotVerified */ echo __('Product Code: ') ?></span></label>
                <div class="control">
                    <input name="entity_id" id="entity_id" title="<?php /* @escapeNotVerified */ echo __('Product ID') ?>" readonly="readonly" style="border: none;" class="input-text" type="text" />
                </div>
            </div>
        </div>

        <div class="field name required">
            <div class="col-sm-6">
                <label class="label" for="first_name"><span><?php /* @escapeNotVerified */ echo __('First Name:') ?></span></label>
                <div class="control">
                    <input name="first_name" id="first_name" title="<?php /* @escapeNotVerified */ echo __('First Name') ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
        </div>

        <div class="field name required">
            <div class="col-sm-6">
                <label class="label" for="last_name"><span><?php /* @escapeNotVerified */ echo __('Last Name:') ?></span></label>
                <div class="control">
                    <input name="last_name" id="last_name" title="<?php /* @escapeNotVerified */ echo __('Last Name') ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
        </div>

        <div class="field name required">
            <div class="col-sm-6">
                <label class="label" for="address"><span><?php /* @escapeNotVerified */ echo __('Address:') ?></span></label>
                <div class="control">
                    <input name="address" id="address" title="<?php /* @escapeNotVerified */ echo __('Address') ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
        </div>

        <div class="field name required">
            <div class="col-sm-6">
                <label class="label" for="town"><span><?php /* @escapeNotVerified */ echo __('Town:') ?></span></label>
                <div class="control">
                    <input name="town" id="town" title="<?php /* @escapeNotVerified */ echo __('Town') ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
        </div>

        <div class="field name required">
            <div class="col-sm-6">
                <label class="label" for="post_code"><span><?php /* @escapeNotVerified */ echo __('Post Code:') ?></span></label>
                <div class="control">
                    <input name="post_code" id="post_code" title="<?php /* @escapeNotVerified */ echo __('Post Code') ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
        </div>

        <div class="field name required">
            <div class="col-sm-6">
                <label class="label" for="company_name"><span><?php /* @escapeNotVerified */ echo __('Company Name:') ?></span></label>
                <div class="control">
                    <input name="company_name" id="company_name" title="<?php /* @escapeNotVerified */ echo __('Company Name') ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
        </div>

        <div class="field email required">
            <div class="col-sm-6">
                <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email:') ?></span></label>
                <div class="control">
                    <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
        </div>

        <?php if ($this->getData('cc_enable_phoneno')) { ?>
        <div class="field telephone">
            <div class="col-sm-6">
                <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone Number:') ?></span></label>
                <div class="control">
                    <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text" type="text" />
                </div>
            </div>
        </div>
        <?php } ?>

        <div class="field name required">
            <div class="col-sm-6">
                <label class="label" for="subject"><span><?php /* @escapeNotVerified */ echo __('Subject:') ?></span></label>
                <div class="control">
                    <input name="subject" id="subject" title="<?php /* @escapeNotVerified */ echo __('Subject') ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
        </div>

        <div class="field name required">
            <div class="col-sm-6">
                <label class="label" for="time_call"><span><?php /* @escapeNotVerified */ echo __('What time is the best for us to call you?' ) ?></span></label>
                <div class="control">
                    <select name="time_call">
                        <option value="morning" selected="selected">In the morning (8:00 - 12:00)</option>
                        <option value="afternoon">In the afternoon (12:00 - 18:00)</option>
                        <option value="anytime">Any time (8:00 - 18:00)</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="field comment required">
            <div class="col-sm-12"
                <label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?></span></label>
                <div class="control">
                    <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
                </div>
            </div>
        </div>

        <?php if ($this->getData('cc_enable_recaptcha')) { ?>
        <div class="field comment required">
            <div class="col-sm-6">
                <label class="label" for="captcha"><span><?php /* @escapeNotVerified */ echo __('ReCaptcha') ?></span></label>
                <div class="control">
                    <script src="https://www.google.com/recaptcha/api.js"></script>
                    <div class="g-recaptcha" data-sitekey="<?php echo $captchaSitekey;?>" data-theme="<?php echo $captchaTheme; ?>"></div>
                </div>
            </div>
        </div>       
        <?php } ?>
        
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <div class="col-sm-12">
                <input type="hidden" name="currUrl" id="currUrl" value="<?php echo $currPageUrl; ?>" />
                <input type="hidden" name="enablerecaptcha" id="enablerecaptcha" value="<?php echo $this->getData('cc_enable_recaptcha'); ?>" />
                <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                    <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                </button>
            </div>
        </div>
    </div>
</form>
<?php } ?>